name: CI_release

on:
  release:
    types: [published]
permissions:
  contents: write

jobs:
  build-release:
    uses: ./.github/workflows/CI_build.yml

  release:
    runs-on: windows-latest
    needs: [build-release]
    steps:
    - name: Checkout repo
      uses: actions/checkout@v6

    - name: install-python
      uses: actions/setup-python@v6

    - name: install-dependencies
      run: |
        python -m pip install --upgrade pip
        pip install docopt-ng ghapi github3.py "smart-open[http]"

    - name: set-release-info
      id: set_release_info
      env:
        GITHUB_OBJECT: ${{ toJson(github) }}
      run: |
        python github-action-scripts/get_npp_release_info.py --info plugin_info.json >> $env:GITHUB_OUTPUT

    - name: get-dispatch-token
      id: get_dispatch_token
      uses: actions/create-github-app-token@v3
      with:
        app-id: ${{ secrets.TOKEN_GETTER }}
        private-key: ${{ secrets.TOKEN_KEY }}
        permission-contents: write
        repositories: nppPluginList

    - name: get-push-token
      id: get_push_token
      uses: actions/create-github-app-token@v3
      with:
        app-id: ${{ secrets.TOKEN_GETTER }}
        private-key: ${{ secrets.TOKEN_KEY }}
        permission-contents: write
        permission-pull-requests: write
        permission-workflows: write
        repositories: nppPluginList
        skip-token-revoke: true

    - name: update-version-info
      uses: peter-evans/repository-dispatch@v4
      with:
        token: ${{ steps.get_dispatch_token.outputs.token }}
        repository: ThosRTanner/nppPluginList
        event-type: version_updated
        client-payload: |-
          {
            "token": "${{ steps.get_push_token.outputs.token }}",
            "info": ${{ toJson(steps.set_release_info.outputs.info) }}
          }
