name: CI_release

on:
  release:
    types: [published]
permissions:
  contents: write

jobs:
  build-release:
    uses: ./.github/workflows/CI_build.yml

  release:
    runs-on: windows-latest
    needs: [build-release]
    steps:
    - name: get-data
      uses: actions/download-artifact@v4

    - name: update-notes
      env:
        GH_TOKEN: ${{ github.token }}
      run: |
        echo "# Plugin Checksums" > Notes
        echo "" >> Notes
        echo "| File | SHA-256 |" >> Notes
        echo "| - | - |" >> Notes
        $repo = "${{ github.repository }}"
        Get-ChildItem -Directory | ForEach-Object {
            $source = $_.Name
            $dest = "$source.zip"
            Compress-Archive -Path "$source/*" -DestinationPath "$dest"
            $sha256 = (Get-FileHash "$dest").Hash
            echo "| $dest | $sha256 |" >> Notes
            gh release upload "${{ github.event.release.tag_name }}" "$dest" -R "$repo"
        }
        gh release edit "${{ github.event.release.tag_name }}" --notes-file Notes -R "$repo"
